
## 해결문제 01 

---


리스트 함수를 활용하여 아래의 지시 사항을 수행하세요.

1. numbers라는 빈 리스트를 만들고 리스트를 출력한다.
2. append를 이용해서 numbers에 1, 7, 3, 6, 5, 2, 13, 14를 순서대로 추가한다. 그 후 리스트를 출력한다.
3. numbers 리스트의 원소들 중 홀수는 모두 제거한다. 그 후 다시 리스트를 출력한다.
4. numbers 리스트의 인덱스 0 자리에 20이라는 수를 삽입한 후 출력한다.
5. numbers 리스트를 정렬한 후 출력한다.


![image.png]()


## 해결문제 02 

---


기상청에서 제공하는 2020년 3월 1일에서 3월 31일까지의 평균기온 정보를 참고하여 다음을 구하시오. (단, 평균기온이 동일한 날은 없음)

+ 최고기온인 날
+ 최저기온인 날
+ 3월 평균기온

![image.png]()

In [ ]:
#부산 3월 기온
temp = [10.8, 8.5, 8.7, 7.9, 5.1, 
        8.1, 8.2, 10.4, 11, 9.9, 
        7.8, 9.5, 11.6, 8.2, 7.7, 
        6.6, 11.1, 12.2, 12.6, 10.4, 
        13.7, 14.1, 12.6, 11.5, 13, 
        14.5, 13.7, 9.4, 10.4, 11.6, 12.9]


## 해결문제 03 

---


기상청 공공데이터 사이트(https://data.kma.go.kr/stcs/grnd/grndTaList.do?pgmNo=70)에서 2020년 1월에서 11월까지 부산 평균기온을 조사해서 2020년의 전체 평균기온을 구하시오.

In [ ]:
avgtemp = [6.4, 7.1, 10.4, 12.6, 17.9, 22.4, 22.1, 27.2, 21.9, 17.3, 12.4]


## 해결문제 04 

---
 다음은 2010~2019년 기온 데이터(년도, 평균, 최소, 최대)이다. 

```
y = [2010,  2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
yavg = [14.9, 14.6, 14.5, 15.3, 15.1, 15.4, 15.7, 15.2, 15.1, 15.7]
ymax = [34.1, 33, 34.5, 35, 32.9, 33.5, 37.3, 36.2, 36.4, 35]
ymin = [19, 18.8, 18.6, 19.5, 19.2, 19.5, 19.8, 19.6, 19.2, 19.8]
```

+ 홀수년도만 출력
+ 년도 출력하기
+ 년도와 평균기온 딕셔너리 만들기
+ 평균기온 최소일 때 해당년도 추출하기 예) 2012년 – 14.5℃
+ 최고기온 최대일 때 해당년도 추출하기 예) 2016년 – 19.6℃ 
+ 최저기온 최소일 때 해당년도 추출하기 예) 2012년 – 18.6℃

https://github.com/lsa-src/winterSch/blob/main/weatherStatistics.py

In [ ]:
y=[2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
yavg=[14.9,14.6,14.5,15.3,15.1,15.4,15.7,15.2,15.1,15.7]
ymax=[34.1,33,34.5,35,32.9,33.5,37.3,36.2,36.4,35]
ymin=[19,18.8,18.6,19.5,19.2,19.5,19.8,19.6,19.2,19.8]


#홀수년도
yodd = [] #빈리스트 생성, 홀수년을 찾아서 넣음
for item in y:
    if item % 2 == 1:
        yodd.append(item)
print(f'홀수년: {yodd}')